# Generated by Django 6.0.5 on 2026-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='campus_code',
            field=models.CharField(help_text='Example: KAM, for Kamulu', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='subdomain',
            field=models.CharField(help_text='Example: mombasa, for mombasa.app.skylon.org', max_length=50, unique=True),
        ),
    ]
