# Generated by Django 6.0.5 on 2026-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_paymenthistory_processed_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_use_consent',
            field=models.BooleanField(default=False, help_text='Explicit parental choice regarding social media marketing and promotional image use.'),
        ),
    ]
