# Generated by Django 6.0.5 on 2026-06-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_image_use_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], db_index=True, default=1, help_text='The academic term the student joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='The calendar year the student joined (e.g., 2026)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='image_use_consent',
            field=models.BooleanField(default=True, help_text='Explicit parental choice regarding social media marketing and promotional image use.'),
        ),
    ]
