# Generated by Django 6.0.5 on 2026-06-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_enrollment_term_student_enrollment_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(blank=True, help_text='The closing calendar date of this term block.', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(blank=True, help_text='The opening calendar date of this term block.', null=True),
        ),
    ]
