# Generated by Django 6.0.5 on 2026-06-08 13:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_term_end_date_term_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='e.g., Kamulu Zone A, Nyali Axis', max_length=150, unique=True)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='extras_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='extras_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transport_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tuition_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_items',
            field=models.ManyToManyField(blank=True, to='students.extraitem'),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_route',
            field=models.ForeignKey(blank=True, help_text='Assigned route/location determining their transport billing.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.transportroute'),
        ),
    ]
