# Generated by Django 6.0.5 on 2026-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_extraitem_transportroute_invoice_extras_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)')], default='USD', help_text="The local currency label used for this specific campus's invoices.", max_length=3),
        ),
    ]
