# Generated by Django 6.0.5 on 2026-06-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_campus_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='e.g., EUR, NGN, KES', max_length=3, unique=True)),
                ('rate_to_reporting_currency', models.DecimalField(decimal_places=6, help_text='Multiply local currency by this factor to convert to HQ reporting currency.', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campus',
            name='currency_code',
            field=models.CharField(choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)')], default='$', help_text="The local currency label used for this specific campus's invoices.", max_length=3),
        ),
    ]
