# Generated by Django 6.0.5 on 2026-06-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_exchangerate_alter_campus_currency_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportroute',
            old_name='location_name',
            new_name='route_name',
        ),
        migrations.AddField(
            model_name='transportroute',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='students.campus'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='currency_code',
            field=models.CharField(choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'British Pound (£)'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira (₦)'), ('Xaf', 'Central African CFA'), ('Xof', 'West African CFA'), ('Rnd', 'South African Rand (R)')], default='KES', help_text="The local currency label used for this specific campus's invoices.", max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='transportroute',
            unique_together={('campus', 'route_name')},
        ),
    ]
