# Generated by Django 6.0.5 on 2026-06-09 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_location_name_transportroute_route_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportroute',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='students.campus'),
        ),
    ]
