# Generated by Django 6.0.5 on 2026-06-10 00:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_transportroute_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='previous_arrears',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unpaid balance carried forward from the immediate previous term.', max_digits=10),
        ),
    ]
