# Generated by Django 6.0.5 on 2026-06-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_invoice_previous_arrears'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='neighborhood',
            new_name='address',
        ),
    ]
