# Generated by Django 6.0.5 on 2026-06-22 20:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_rename_neighborhood_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='scholarship_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='current_term_scholarship',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='on_scholarship',
            field=models.BooleanField(default=False, help_text='Flag indicating if the student is actively receiving a fee waiver/bursary.'),
        ),
    ]
