# Generated by Django 6.0.5 on 2026-06-23 01:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_invoice_scholarship_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='scholarship_amount',
            new_name='scholarship_applied',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='current_term_scholarship',
            new_name='scholarship_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='approver_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='scholarship_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_scholarship_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='The administrative user who signed off or reviewed this scholarship request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scholarships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='proposed_scholarship_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount requested by local staff awaiting review.', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_status',
            field=models.CharField(choices=[('NONE', 'No Scholarship'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Active'), ('REJECTED', 'Rejected')], default='NONE', max_length=15),
        ),
    ]
