# Generated by Django 6.0.5 on 2026-06-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_rename_scholarship_amount_invoice_scholarship_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='on_scholarship',
        ),
    ]
