# Generated by Django 6.0.5 on 2026-06-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_director',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a campus director with elevated permissions.'),
        ),
    ]
