# Generated by Django 6.0.5 on 2026-06-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_director',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a director with elevated permissions.'),
        ),
    ]
