# Generated by Django 6.0.5 on 2026-06-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('students', '0007_term_end_date_term_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='students.term'),
        ),
    ]
